<nav>  
            <a href="index.html"><img src="../images/logo.jpg" id="logo" alt="melbourne possums logo"></a>
            <ul id="header">  
                <li><a href="index.html" class="directory">Home</a></li>  
                <li><a href="../project1/jobs.html" class="directory">Job Opportunities</a></li> 
                <li><a href="../project1/about.html" class="directory">About</a></li>  
                <li><a href="../project1/apply.html" class="directory">Apply</a></li>  
            </ul>  
        </nav>