<nav>  
    <a href="index.html"><img src="../images/logo.jpg" id="logo" alt="melbourne possums logo"></a>
    <ul id="header">  
        <li><a href="./index.php" class="directory">Home</a></li>  
        <li><a href="./jobs.php" class="directory">Job Opportunities</a></li> 
        <li><a href="./about.php" class="directory">About</a></li>  
        <li><a href="./apply.php" class="directory">Apply</a></li>  
    </ul>  
</nav>